### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by timvw** [anboralabs/sqlfluff-intellij-community#29]
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 518, in <module>
    def lint(
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 218, in core_options
    get_plugin_manager().hook.get_templaters()
  File "/usr/local/lib/python3.10/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/site-packages/dbt_osmosis/dbt_templater/__init__.py", line 4, in <module>
    import dbt_osmosis.core.server_v2
  File "/usr/local/lib/python3.10/site-packages/dbt_osmosis/core/server_v2.py", line 14, in <module>
    from dbt_osmosis.core.osmosis import DbtProject, DbtProjectContainer, has_jinja
  File "/usr/local/lib/python3.10/site-packages/dbt_osmosis/core/osmosis.py", line 49, in <module>
    from dbt.contracts.graph.parsed import ColumnInfo
ModuleNotFoundError: No module named 'dbt.contracts.graph.parsed'

pip freeze | grep -E "(dbt|sql)"                                                                          
dbt-athena-community==1.0.4
dbt-core==1.5.1
dbt-extractor==0.4.1
dbt-postgres==1.5.1
dbt-spark==1.5.0
pytest-dbt-core==0.2.1
sqlfluff==2.1.1
sqlparams==5.1.0
sqlparse==0.4.3

Build #PY-231.9011.38, built on May 16, 2023

**Comment by dalgarins** [comment]
@timvw it seems a problem with your python packages installed on your machine, try this:

open your terminal and execute the command, sqlfluff.

paste the result here.

**Comment by timvw** [comment]
sqlfluff from the command line works just fine...

sqlfluff version    -> 2.1.1

sqlfluff lint                                                                                                             
=== [dbt templater] Sorting Nodes...                                                                                                                                                                                    
=== [dbt templater] Compiling dbt project...                                                                                                                                                                            
=== [dbt templater] Project Compiled.                                                                                                                                                                                   
....
All Finished 📜 🎉!

**Comment by timvw** [comment]
After removing /usr/local/bin/sqlfluff (and only having sqlfluff in my venv the error is gone.. but nothing seems to happen anymore)..

**Comment by dalgarins** [comment]
@timvw if you fix the local package sqlfluff you need to restart the IDE, and also test the command sqlfluff version inside IDE terminal, let me know if it works.

**Comment by dalgarins** [comment]
@timvw is it fixed the issue?
